baseURL = 'https://prototo.github.io/mimi/'
locale = 'en-us'
title = 'Disability, Horror, & Pop Culture'
theme = 'sickvacay'

[params.logo]
src = '/images/logo.webp'
alt = 'Amy Mackelden'

[markup.goldmark.parser.attribute]
  block = true

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
tag = 'tags'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
