baseURL = 'https://example.org/'
locale = 'en-US'
title = 'My New Hugo Project'

[menus]
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 10

  [[menus.main]]
    name = 'Interviews'
    pageRef = '/interviews'
    weight = 20

  [[menus.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.128.0'
